os: linux
arch:
  - arm64
language: python
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis coverage
script: tox
after_success:
  - coveralls
after_script:
  - coverage erase
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: vP1+3+yAU7CHwAsjtimFLZ2ixaoMUgCeQLf64i+/Vlj4CLjTi4MbYdA+Vkw0MkUTqSiCN6FUdIk2ivpKze87KjSiszQvJNBAQHbgq8ehs4rHsRKOsG2sNTBGi/+8qlSoKfRsNuwQ5BUNgfjlORbOEgcCkG0hZyKSJfbVgJKbPBWeZFKlRdPDFf+vpi6H6bhRUliq/f3Y9LfSwi1FXgZ6lyndsgJJtI+5fklXC39xf59K15J2tajXq3fFYfCyqZ1iAIyvtTkDxGTpf49T8Z5NPB7U1IdXln2+Hwwx/C/BHvpjvXXTkbf0+koyXe/1rQ+xFmAv7ufom6BZXbOCihYnIUUlXYi8C/9O3rkJ77NXiVtCwLvWaUqB92YtPARMFnx/KKRUcitZclin/Z7jpZM/epc3o+NVevfTj+8hygg86/P8tNyr2lzPi0j+v5sZkIhYplLxUNPaJuiEfQH5DTRSp0Xml/hUylx4F/mtxKO6qfD1kFNY5sd93tigh5VtnqFFQdOVsYdqrW5Sc2i+LXN4oOlaSUZuCh2BKK3liZsMvuzUrjuo2pQtFTxlzWr9WerSpeyIh22GZa7VdurqqA4nsfpyn/81O3IlQWvCXOL/9qZwTJxoGm45JGCdVDcfX9nFL05cRXziKbGe3SV3oozYqob7mgdkYA/Jbwt2Y+frNLo=
  on:
    tags: true
    branch: master
    repo: carlculator/timeseriesx
    python: 3.9
