language: python
env:
  global:
    - CC_TEST_REPORTER_ID=f0f58a84abac073113c3a0d8f9d1315fa83ed580a3d5f95fe9fdfeecaff3302d
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis coverage
before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: tox
after_script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.9" ]]; then ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT; fi
  - coverage erase
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: carl_culator
  username: "__token__"
  password:
    secure: Yysk6FLr+Mn2W1LdvCoyZaFshPARvaESonoiSHLxFK0d4tkkEiAwDsM/UXzn4dLJyJscYwYVXcFklJM3dVBZo1+EcWQQpj3QIEopaX09YHpgj6wymEodlqELWGdIu7mm2HTaYRhdqM6sqsrvgK4Zr2NEDAoIj0XqXNLkMQrKz2Y0QByRISDsHIuQbcUt80u37ezRI1/sk4/xaMlyH+HHlxzvyebXb6h9EsGPM85g8qhT9vw1JCzjxBOv6Wb5s72elxMRfFw1R0AQX+JdKE7Hy20ick6vWPVSOd5h1ql2wWx9nIpoA9jLR5be78lX5+WgtMewtE14Lo9W/MWj5jTCOItLh5u0asL8EPn/BfE7VX7jiKUrTdKD0sF/drIPINGXGirUnheamfvverqY0jtZoDl16OdoerbkFCKsYJcTVZpS3lDJLSgl2dUCxb4y+veenjSVgs4lKBCxuNuOlnrPkbHrVCa8BKR8wj4RE7g1jLRTs9qRmPjVauQhXk6wqKPzVsvN2MCiOkkDV1+x1uXmNCNGHohB8CSQ7CNevRDIpy58ec7p2tKK0BeEM7ixjnkVTrjAUvd/CNbczQAOsfHz2pqpvjGWU2XRc5H2tw9CXOEf2NKo25XW0MJQmVQPMyZFwFK0KOaTaPzRArvbZSpfnVZXDiRv4hG2V+ZcEq89FOc=
  on:
    tags: true
    repo: carlculator/timeseriesx
    python: 3.9
